jenkins:
  systemMessage: "Jenkins настроен через Configuration as Code"

  numExecutors: 1
  mode: NORMAL
  labelString: "master"

  nodes:
    - permanent:
        name: "dev-cloud"
        remoteFS: "/home/jenkins/agent"
        mode: EXCLUSIVE
        labelString: "slave"
        retentionStrategy: "always"
        launcher:
          ssh:
            host: "194.113.34.197"
            port: 2222
            credentialsId: "jenkins-agent-ssh-key"
            sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "${JENKINS_ADMIN_ID}"
          name: "${JENKINS_ADMIN_ID}"
          password: "${JENKINS_ADMIN_PASSWORD}"

  crumbIssuer: "standard"

  remotingSecurity:
    enabled: true

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "gihub-ssh"
              description: "Доступ к GitHub"
              username: "git"
              privateKeySource:
                directEntry:
                  privateKey: "${github_ssh_key}"

security:
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "acceptFirstConnectionStrategy"

unclassified:
  location:
    adminAddress: "${JENKINS_ADMIN_EMAIL}"

tool:
  git:
    installations:
      - name: "Default"
        home: "git"

jobs:
  - script: |
      pipelineJob('taxi-manager-ci') {
        description('CI для проекта taxi-manager. Создан через Job DSL.')

        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('ssh://git@ssh.github.com:443/metacortex687/taxi-manager.git')
                  credentials('gihub-ssh')
                }

                branch('*/main')
              }
            }

            scriptPath('Jenkinsfile')
            lightweight()
          }
        }
      }